# Generated by Django 4.2.13 on 2024-05-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='for_date',
            field=models.DateField(),
        ),
    ]
