# Generated by Django 4.2.11 on 2024-07-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_for_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='for_date',
        ),
    ]
